# File: .readthedocs.yaml

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Install mpi (for vcstools)
build:
  apt_packages:
    - python3-mpi4py
    - libopenmpi-dev

# Explicitly set the version of Python and its requirements
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py